# Company Information
company_name: Adassa Enterprise Solutions, Inc.
domain_name: adassa.adassa.com.jm
address_line: Kingston
country: Jamaica
company_email: mail@adassa.com.jm
description: This is the Adassa Academy website.
meta_description: online education, e-learning, primary and secondary school mathematics, CSEC, CXC 

# Site Information
title: Adassa Academy
author: Desmond Bennett
baseurl: ""
url: https://academy.adassa.com.jm

# Social Links
facebook_link: https://www.facebook.com/desmondpbennett
twitter_link: https://twitter.com/DPB_and_A
github_link: https://github.com/Adassa-Enterprise-Solutions/

disqus: false
disqus_shortname: adassa_academy

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate-v2

jekyll_admin:
  hidden_links:
    - configuration
  homepage: "pages"  